# Generated by Django 3.2.9 on 2021-11-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=200, unique=True, verbose_name='项目名称')),
                ('leader', models.CharField(help_text='负责人', max_length=48, verbose_name='负责人')),
                ('desc', models.CharField(blank=True, help_text='项目简述', max_length=48, null=True, verbose_name='项目简述')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'PRO_PROJECT',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='环境名称', max_length=128, verbose_name='环境名称')),
                ('host', models.URLField(help_text='主机地址', verbose_name='主机地址')),
                ('db_config', models.JSONField(blank=True, default=dict, help_text='数据库设置', verbose_name='数据库设置')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': '项目环境',
                'verbose_name_plural': '项目环境',
                'db_table': 'PRO_ENVIRONMENT',
            },
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='unique_env_name'),
        ),
    ]
