# Generated by Django 3.2.9 on 2021-11-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='课程名称')),
            ],
            options={
                'db_table': 'CRM_COURSE',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='班级名称')),
                ('num', models.CharField(max_length=20, verbose_name='班期')),
            ],
            options={
                'db_table': 'CRM_GRADE',
            },
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idno', models.CharField(default='', max_length=18, verbose_name='身份证号码')),
                ('college', models.CharField(default='', max_length=48, verbose_name='毕业学校')),
            ],
            options={
                'db_table': 'CRM_STUDENTDETAIL',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='学生姓名')),
                ('age', models.SmallIntegerField(default='', verbose_name='年龄')),
                ('sex', models.SmallIntegerField(default=1, verbose_name='性别')),
                ('qq', models.CharField(default='', max_length=20, verbose_name='QQ号')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='crm.studentdetail')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.grade')),
            ],
            options={
                'db_table': 'CRM_STUDENT',
            },
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='金额')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.student')),
            ],
            options={
                'db_table': 'CRM_ENROLL',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='crm.Enroll', to='crm.Student'),
        ),
    ]
